name: Build JRE Image

on:
  push:
    branches: [ main ]
    paths:
      - 'images/Dockerfile.jre'
      - 'images/Dockerfile.base'
      - '.github/workflows/build-jre.yml'
      - '.github/workflows/shared-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/Dockerfile.jre'
      - 'images/Dockerfile.base'
      - '.github/workflows/build-jre.yml'
      - '.github/workflows/shared-build.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  build-jre:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/shared-build.yml
    with:
      image_name: 'jre'
      dockerfile_path: 'images/Dockerfile.jre'
      context_path: './images/'
      size_target: '<220MB'
      test_command: 'echo "JRE runtime only - requires pre-compiled .class files"'
    secrets: inherit