name: Build C Image

on:
  push:
    branches: [ main ]
    paths:
      - 'images/Dockerfile.c'
      - 'images/Dockerfile.base'
      - '.github/workflows/build-c.yml'
      - '.github/workflows/shared-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/Dockerfile.c'
      - 'images/Dockerfile.base'
      - '.github/workflows/build-c.yml'
      - '.github/workflows/shared-build.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  build-c:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/shared-build.yml
    with:
      image_name: 'c'
      dockerfile_path: 'images/Dockerfile.c'
      context_path: './images/'
      size_target: '<110MB'
      test_command: '/usr/local/bin/program'
      test_file_content: |
        #include <stdio.h>
        int main() { 
            printf("Test successful\n"); 
            return 0; 
        }
      test_file_extension: 'c'
    secrets: inherit